services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env
